### The numpy random seed is a numerical value that generates a new set or repeats pseudo-random numbers. The value in the numpy random seed saves the state of randomness. If we call the seed function using value 1 multiple times, the computer displays the same random numbers. 

In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
# Generate and print random float
np.random.rand()

0.5488135039273248

In [4]:
# generate an array of random numbers
np.random.rand(2, 5)

array([[0.71518937, 0.60276338, 0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276, 0.38344152, 0.79172504]])

In [6]:
np.random.randint(2, 5, 10)

array([2, 3, 3, 3, 3, 2, 3, 2, 2, 3])

In [7]:
# Generate a 2D array of random values
np.random.randint(low = 2, high = 15, size = (3, 5))

array([[ 2,  4,  5, 10,  3],
       [ 5,  5,  5,  9,  2],
       [ 3, 11, 11,  2, 12]])

In [8]:
# NumPy is imported, seed is set

# Starting step
step = 50

# Roll the dice
dice = np.random.randint(low=1, high=7, size=(1))

# Finish the control construct
if dice <= 2 :
    step = step - 1
elif dice >= 3 and dice <=5:
    step = step + 1
else :
    step = step + np.random.randint(1,7)

# Print out dice and step
print(dice)
print(step)

[5]
51


In [ ]:
random_values = np.random