In [1]:
house = [["hallway", 11.25], 
         ["kitchen", 18.0], 
         ["living room", 20.0], 
         ["bedroom", 10.75], 
         ["bathroom", 9.50]]

for x in house:
    #print(x[0])
    #print(x[1])
     #print("the " + str(x[0] + " is " + str(x[1]))) 
     print(f'the {x[0]} is {x[1]}')

the hallway is 11.25
the kitchen is 18.0
the living room is 20.0
the bedroom is 10.75
the bathroom is 9.5


## 2D Numpy Arrays iteration

In [2]:
import numpy as np

In [3]:
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

#creating an array for both
meas = np.array([np_height, np_weight])
print(meas)

#iterating over a 2D numpy array
#The for loop simpy prints out each array
for var in meas:
    print(var)
    
#To iterate through each value we have to use: the function (np.nditer())
for val in np.nditer(meas):
    print(val)

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]
[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]
1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7


In [4]:
import pandas as pd

In [5]:
country = ['Brazil', 'Russia', 'India', 'China', 'South Africa']
capital = ['Brasilia', 'Moscow', 'New Delhi', 'Beijing', 'Pretoria']
area = [8.516, 17.100, 3.286, 9.597, 1.221]
population = ['200.4B', '143.5B', '1252.0B', '1357.0B', '52.9B']

In [6]:
brics = {'country':country, 'capital':capital, 'area':area, 'population':population}
print(brics)

{'country': ['Brazil', 'Russia', 'India', 'China', 'South Africa'], 'capital': ['Brasilia', 'Moscow', 'New Delhi', 'Beijing', 'Pretoria'], 'area': [8.516, 17.1, 3.286, 9.597, 1.221], 'population': ['200.4B', '143.5B', '1252.0B', '1357.0B', '52.9B']}


In [7]:
new_brics = pd.DataFrame(brics)
print(new_brics)

        country    capital    area population
0        Brazil   Brasilia   8.516     200.4B
1        Russia     Moscow  17.100     143.5B
2         India  New Delhi   3.286    1252.0B
3         China    Beijing   9.597    1357.0B
4  South Africa   Pretoria   1.221      52.9B


In [8]:
print(new_brics)

        country    capital    area population
0        Brazil   Brasilia   8.516     200.4B
1        Russia     Moscow  17.100     143.5B
2         India  New Delhi   3.286    1252.0B
3         China    Beijing   9.597    1357.0B
4  South Africa   Pretoria   1.221      52.9B


In [9]:
print(new_brics['area'])

0     8.516
1    17.100
2     3.286
3     9.597
4     1.221
Name: area, dtype: float64


In [10]:
brics_series = pd.Series(data = new_brics['area'], name='area')
print(brics_series)

0     8.516
1    17.100
2     3.286
3     9.597
4     1.221
Name: area, dtype: float64


In [11]:
row_labels = ['BR', 'RU', 'IN', 'CH', 'SA']
new_brics.index = row_labels
print(new_brics)

         country    capital    area population
BR        Brazil   Brasilia   8.516     200.4B
RU        Russia     Moscow  17.100     143.5B
IN         India  New Delhi   3.286    1252.0B
CH         China    Beijing   9.597    1357.0B
SA  South Africa   Pretoria   1.221      52.9B


In [12]:
#brics = pd.DataFrame(brics, index = row_labels)
#print(brics)

In [13]:
#brics = pd.DataFrame(new_brics, index = row_labels)
#print(brics)

In [14]:
new_brics.to_csv('brics information.csv', sep = ',', index = True)

In [15]:
new_brics = pd.read_csv('brics information.csv', index_col = 0)
print(new_brics)

         country    capital    area population
BR        Brazil   Brasilia   8.516     200.4B
RU        Russia     Moscow  17.100     143.5B
IN         India  New Delhi   3.286    1252.0B
CH         China    Beijing   9.597    1357.0B
SA  South Africa   Pretoria   1.221      52.9B


In [16]:
 new_brics

country    capital    area population
BR        Brazil   Brasilia   8.516     200.4B
RU        Russia     Moscow  17.100     143.5B
IN         India  New Delhi   3.286    1252.0B
CH         China    Beijing   9.597    1357.0B
SA  South Africa   Pretoria   1.221      52.9B

## Looping Data Structures

In [17]:
new_brics = pd.read_csv('brics information.csv', index_col = 0)
# print(new_brics)

# the for loop only give us the column
for val in new_brics:
    print(val)

country
capital
area
population


### iterrows

In [18]:
# It gives us the label of the row and the values of each row.
for lab, row in new_brics.iterrows():
    print(lab)
    print(row)

BR
country         Brazil
capital       Brasilia
area             8.516
population      200.4B
Name: BR, dtype: object
RU
country       Russia
capital       Moscow
area            17.1
population    143.5B
Name: RU, dtype: object
IN
country           India
capital       New Delhi
area              3.286
population      1252.0B
Name: IN, dtype: object
CH
country         China
capital       Beijing
area            9.597
population    1357.0B
Name: CH, dtype: object
SA
country       South Africa
capital           Pretoria
area                 1.221
population           52.9B
Name: SA, dtype: object


In [19]:
for lab, row in new_brics.iterrows():
    print(lab + ": " + row["capital"])

BR: Brasilia
RU: Moscow
IN: New Delhi
CH: Beijing
SA: Pretoria


## Adding a column

In [20]:
for lab, rows in new_brics.iterrows():
    
    #Creating a series on every iteration but it is inefficient
    new_brics.loc[lab, "name_length"] = len(row["country"])

print(new_brics)

         country    capital    area population  name_length
BR        Brazil   Brasilia   8.516     200.4B         12.0
RU        Russia     Moscow  17.100     143.5B         12.0
IN         India  New Delhi   3.286    1252.0B         12.0
CH         China    Beijing   9.597    1357.0B         12.0
SA  South Africa   Pretoria   1.221      52.9B         12.0


In [21]:
new_brics

country    capital    area population  name_length
BR        Brazil   Brasilia   8.516     200.4B         12.0
RU        Russia     Moscow  17.100     143.5B         12.0
IN         India  New Delhi   3.286    1252.0B         12.0
CH         China    Beijing   9.597    1357.0B         12.0
SA  South Africa   Pretoria   1.221      52.9B         12.0

In [22]:
new_brics['name_length'] = new_brics['country'].apply(len)
print(new_brics)

         country    capital    area population  name_length
BR        Brazil   Brasilia   8.516     200.4B            6
RU        Russia     Moscow  17.100     143.5B            6
IN         India  New Delhi   3.286    1252.0B            5
CH         China    Beijing   9.597    1357.0B            5
SA  South Africa   Pretoria   1.221      52.9B           12


In [23]:
new_brics

country    capital    area population  name_length
BR        Brazil   Brasilia   8.516     200.4B            6
RU        Russia     Moscow  17.100     143.5B            6
IN         India  New Delhi   3.286    1252.0B            5
CH         China    Beijing   9.597    1357.0B            5
SA  South Africa   Pretoria   1.221      52.9B           12

## SQUARE BRACKETS; allow column access: brics[['country', 'capital']] and row access through only slicing: brics[1:4]
                    
## ROW AND COLUMN ACCESSING; loc and iloc

In [24]:
#loc

new_brics.loc['RU']

country        Russia
capital        Moscow
area             17.1
population     143.5B
name_length         6
Name: RU, dtype: object

In [25]:
#Dataframe output
new_brics.loc[['RU']]

country capital  area population  name_length
RU  Russia  Moscow  17.1     143.5B            6

## Series a column of multiple rows
## DataFrame multiple columns with multiple rows

### loc

In [26]:
new_brics.loc[['RU', 'IN', 'CH']]

country    capital    area population  name_length
RU  Russia     Moscow  17.100     143.5B            6
IN   India  New Delhi   3.286    1252.0B            5
CH   China    Beijing   9.597    1357.0B            5

In [27]:
new_brics.loc[['RU', 'IN', 'CH'], ['country', 'capital']]

country    capital
RU  Russia     Moscow
IN   India  New Delhi
CH   China    Beijing

In [28]:
new_brics.loc[:, ['country', 'capital']]

country    capital
BR        Brazil   Brasilia
RU        Russia     Moscow
IN         India  New Delhi
CH         China    Beijing
SA  South Africa   Pretoria

### iloc


In [29]:
new_brics.iloc[[1]]

country capital  area population  name_length
RU  Russia  Moscow  17.1     143.5B            6

In [30]:
new_brics.iloc[[1, 2, 3]]

country    capital    area population  name_length
RU  Russia     Moscow  17.100     143.5B            6
IN   India  New Delhi   3.286    1252.0B            5
CH   China    Beijing   9.597    1357.0B            5

In [31]:
new_brics.iloc[[1, 2, 3], [0, 1]]

country    capital
RU  Russia     Moscow
IN   India  New Delhi
CH   China    Beijing

In [32]:
new_brics.iloc[:, [0, 1]]

country    capital
BR        Brazil   Brasilia
RU        Russia     Moscow
IN         India  New Delhi
CH         China    Beijing
SA  South Africa   Pretoria

## Filtering Pandas DataFrame
### 3 steps: Select the area column, Do comparison on area column, Use result to select countries

In [34]:
# Select the area column
new_brics.loc[:, "area"]

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [35]:
new_brics.iloc[:, 2]

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [37]:
# Do comparison on the area column
is_huge = new_brics["area"]>8


In [38]:
is_huge

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [40]:
# Use the result of selected countries
new_brics[is_huge]

country   capital    area population  name_length
BR  Brazil  Brasilia   8.516     200.4B            6
RU  Russia    Moscow  17.100     143.5B            6
CH   China   Beijing   9.597    1357.0B            5

In [41]:
new_brics[new_brics["area"]>8]

country   capital    area population  name_length
BR  Brazil  Brasilia   8.516     200.4B            6
RU  Russia    Moscow  17.100     143.5B            6
CH   China   Beijing   9.597    1357.0B            5

## Using Boolean Operators

In [42]:
import numpy as np

In [43]:
np.logical_and(new_brics["area"]>8, new_brics["area"]<10)

BR     True
RU    False
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [44]:
new_brics[np.logical_and(new_brics["area"]>8, new_brics["area"]<10)]

country   capital   area population  name_length
BR  Brazil  Brasilia  8.516     200.4B            6
CH   China   Beijing  9.597    1357.0B            5